In [5]:
import sys
import os
sys.path.append('../')
import poker
import numpy as np

In [7]:
po = poker.Poker()
for i,s in enumerate(po.SUIT):
    for j,n in enumerate(po.NUMBER):
        a = np.zeros((4,13), dtype=int)
        a[i,j] = 1
        b = po.str2arr(n+s)
        if np.count_nonzero(a==b):
            pass
        else:
            print(a)
            print(b)


In [8]:
po = poker.Poker()
handstr = ''
for i,s in enumerate(po.SUIT):
    for j,n in enumerate(po.NUMBER):
        handstr += n+s

a = np.ones((4,13), dtype=int)
b = po.str2arr(handstr)
if np.count_nonzero(a==b):
    pass
else:
    print(a)
    print(b)
print('end')

end


In [9]:
po.handrank()

[[1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]]
